# Generated by Django 5.0.2 on 2024-02-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('job_field', models.CharField(max_length=30)),
                ('age', models.DateField()),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('github', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('telegram', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
    ]
